### ISSUE TITLE
What was the whitelist.txt file used for?

### ISSUE THREAD

**Issue by penglu2004** [Hsu-Che-Wei/scKB#3]
Hi, 
When I ran the scKB pipline with example data, I found that only the whitelist files for 10X version 2 and version 3 were provided. So, what was the whitelist used for? And if I want to run the other data type like CELSeq and DropSeq, what can I do with  the whitelist?

Best,
PengLu

**Comment by Hsu-Che-Wei** [comment]
The whitelist is a list of expected barcodes of a specific techniques. It
is used to call valid cells. If you want to use CELSeq or DropSeq, you
should search if there is corresponding whitelist for these techniques.

Best,
Che-Wei
